### ISSUE TITLE
Creo que sería mejor mover los binarios compilados a la página de releases

### ISSUE THREAD

**Issue by fabiopolancoe** [coalio/luacon#1]
¡Hola @coalio! Creo, personalmente y solo como proposición, que sería preferible, y más intuitivo mover los binarios compilados del proyecto a la página de releases del repositorio, para ser de fácil acceso al descargarlo. :wink:

**Comment by fabiopolancoe** [comment]
¡Es un gran proyecto! :sunglasses:

**Comment by coalio** [comment]
Gracias, y tienes razón, no lo había pensado
